project:
  type: website
  output-dir: docs

website:
  title: "wywydubs.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: projects.qmd
        text: Projects
    

format:
  html:
    theme: slate
    css: styles.css
    toc: true

editor: visual


